### ISSUE TITLE
Filename format check looks very strict

### ISSUE THREAD

**Issue by Antonytm** [GAAOPS/Sitecore.Protobuf.Browser#1]
I got an cumulative hotfix from Sitecore Support.
I want to look, what is inside. There are files named `items.master.spe.dat` and `items.master.sxa.dat`.

I try to open them. But I got an error:
![image](https://user-images.githubusercontent.com/647813/225598662-235c8398-496a-4c41-a25d-5fa9d118cd53.png)

**Comment by GAAOPS** [comment]
Hello @Antonytm,

many thanks for taking time and interest to this small repo. Please help me undrestand why do you need this change.

The sitecore protobuf files like "items.master.spe.dat" are containing sparse tree. for example:
![image](https://user-images.githubusercontent.com/8609390/225705784-cf2e3aaa-1db4-4d4b-bcc8-53c80e141383.png)

The System and Modules items are not included inside the "items.master.spe.dat".
The sub module/protobuf files are ment to be small and used in combination with the main files (items.master.dat/items.core.dat/items.web.dat).

There is not an easy way to visualize (as a tree) one of this modules or secondary serialized file without having a main file.

That is the reason that i set a strict validation to include the relevant main file (items.master.dat/items.core.dat/items.web.dat).
Removing the restriction may cause more confusion.

You can select the main file and the secondary file (spe/sxa, ....) to have a full tree.

I undrestand you want to see the items from the package only, i think i can add some sort of filtering to the app.
Currently you have a minimum option, which mark the secondary items (powershell) as red, i can make it more visible with basically hiding the other part of the tree which are not relevant for the secondary package.

Looking forward to hear your opinion.

**Comment by GAAOPS** [comment]
I have just added the filtering and creating a release.
The Read.ME is updated.

**Comment by Antonytm** [comment]
@GAAOPS 
Use case: I got a hotfix from support. I want to understand, what files are included.

**Comment by GAAOPS** [comment]
@Antonytm , you can not open the files as stand alone without the main file, in the file dialog you need to select both for example:
sitecore.master.dat and the the hotfix from support or
sitecore.core.dat and the the hotfix from support.
after that if you are using the release 1.0.1 you can use filtering to filter it down to the items from the support  package.


Sitecore modules and basically secondary files are kind of sparse tree, that means they do not include the whole tree of the master/core/web database. because of that you need to always have a relevant data at hand(ex. items.master.dat) and select it with the relevant module.

**Comment by Antonytm** [comment]
@GAAOPS 

Thank you for this detailed explanation!

Actually, I didn't know that hotfix support files are different. Sorry for initial confusion.

**Comment by GAAOPS** [comment]
@Antonytm , i will close this issue and your PR, I think everything should be clear for now.
